version: "3.9"

x-common-container: &common-container
  restart: unless-stopped
  networks: [elk-network]

x-elk-environment: &elk-environment
  ELASTIC_USERNAME: ${ELASTIC_USERNAME}
  ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

x-elk-build-args: &elk-build-args
  args:
    ELK_VERSION: ${ELK_VERSION}

services:
  web_api:
    <<: *common-container
    container_name: web_api
    build: ./api
    ports: ["5000:80"]

  caddy:
    <<: *common-container
    container_name: caddy
    build: ./caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./client/index.html:/var/www/html/index.html

  elasticsearch:
    <<: *common-container
    container_name: elasticsearch
    build:
      context: ./elasticsearch
      <<: *elk-build-args
    volumes:
      # - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ./secrets:/usr/share/elasticsearch/config/certs:rw
      - ./secrets/kibana:/usr/share/elasticsearch/kibana-server:rw
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      DISCOVERY_TYPE: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      <<: *elk-environment

  kibana:
    <<: *common-container
    container_name: kibana
    build:
      context: ./kibana
      <<: *elk-build-args
    ports: ["5601:5601"]
    depends_on: [elasticsearch]
    #volumes:
      #- ./secrets/kibana:/usr/share/kibana/kibana-server:ro
    environment:
      <<: *elk-environment

  logstash:
    <<: *common-container
    container_name: logstash
    build:
      context: ./logstash
      <<: *elk-build-args
    volumes:
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline.conf:ro
      - secrets-ca:/usr/share/logstash/config/secrets:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      PATH_CONFIG: /usr/share/logstash/pipeline.conf
      <<: *elk-environment
    depends_on: [elasticsearch]

  metricbeat:
    <<: *common-container
    container_name: metricbeat
    build:
      context: ./metricbeat
      <<: *elk-build-args
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - secrets-ca:/usr/share/metricbeat/config/secrets:ro
    depends_on: [elasticsearch]
    environment:
      <<: *elk-environment

networks:
  elk-network:
    driver: bridge

volumes:
  secrets-ca:
  secrets-kibana:
